{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fc8c804-b3c5-4e19-8810-a67d209756ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from scipy.integrate import solve_ivp\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d241d7f-ce32-44a8-930a-75fbed7ec09b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def wolbachia_enhanced_model_temp(t, y, tau, b, v, q, dj, da, D, alpha, beta):\n",
    "    Ju, Ji, Mu, Mi, Fu, Fi = y\n",
    "    Nj = Ju + Ji # Total juveniles\n",
    "    dJu_dt = (1-tau)*b*Fi + b*(1-q*(Mi / (Mi + Mu)))*Fu-(dj + (alpha*Nj)**(beta-1))*Ju - (v*Ju)\n",
    "    dJi_dt = tau*b*Fi - (dj + D + (alpha*Nj)**(beta-1))*Ji - v*Ji\n",
    "    dMu_dt = 0.5*v*Ju - da*Mu\n",
    "    dMi_dt = 0.5*v*Ji - da*Mi\n",
    "    dFu_dt = 0.5*v*Ju - da*Fu\n",
    "    dFi_dt = 0.5*v*Ji - da*Fi\n",
    "    return [dJu_dt, dJi_dt, dMu_dt, dMi_dt, dFu_dt, dFi_dt]\n",
    "\n",
    "# Parameters\n",
    "tau = 0.8 # Fraction of infected offspring from infected mothers, closer to 1\n",
    "b = 7 # Egg-laying, egg-hatching, and survival to the larval stage, could be much bigger\n",
    "v = 4 # Juvenile mosquitoes emerge as adults at a density independent per capita rate, could be much bigger\n",
    "q = 0.9 # Probability of cytoplasmic incompatibility, closer to 1\n",
    "dj = 0.3 # Rate at which juvenile mosquitoes leave the population, temp dependent\n",
    "da = 0.04 # Rate at which adult mosquitoes leave the population, closer to 1/20 or 1/25, temp dependent\n",
    "D = 0.5 # Additional death rate due to infection, experiment with, smaller D value less fitness disadvantage\n",
    "alpha = 1 # Determines equilibrium population size\n",
    "beta = 2 # Determines equilibrium population size\n",
    "\n",
    "# Initial conditions\n",
    "Ju = 10 # Number of uninfected juveniles\n",
    "Ji = 0 # Number of infected juveniles\n",
    "Mu = 10 # Number of uninfected adult males\n",
    "Mi = 0 # Number of infected adult males\n",
    "Fu = 10 # Number of uninfected adult females\n",
    "Fi = 0 # Number of infected adult females\n",
    "initial_conditions = [Ju, Ji, Mu, Mi, Fu, Fi] # Initial conditions in a list\n",
    "\n",
    "# Time span\n",
    "t_span = [0, 1000]\n",
    "t_eval = np.linspace(*t_span, 500)\n",
    "\n",
    "# Solve the ODE\n",
    "sol = solve_ivp(wolbachia_enhanced_model_temp, t_span, initial_conditions, args=(tau, b, v, q, dj, da, D, alpha, beta), t_eval=t_eval)\n",
    "Ju = sol.y[0,499] # Number of uninfected juveniles\n",
    "Ji = 1 # Number of infected juveniles\n",
    "Mu = sol.y[2,499] # Number of uninfected adult males\n",
    "Mi = 0 # Number of infected adult males\n",
    "Fu = sol.y[4,499] # Number of uninfected adult females\n",
    "Fi = 0 # Number of infected adult females\n",
    "initial_conditions = [Ju, Ji, Mu, Mi, Fu, Fi] \n",
    "sol = solve_ivp(wolbachia_enhanced_model_temp, t_span, initial_conditions, args=(tau, b, v, q, dj, da, D, alpha, beta), t_eval=t_eval) # System to solve ODE, differential equation model\n",
    "\n",
    "# Plot the results\n",
    "plt.figure(1, figsize=(4,6))\n",
    "\n",
    "plt.subplot(1, 3, 1)\n",
    "plt.plot(sol.t, sol.y[2], label='Uninfected') # Plot uninfected individuals\n",
    "plt.plot(sol.t, sol.y[3], label='Infected') # Plot infected individuals\n",
    "plt.xlabel('Time') # Time as the independent variable\n",
    "plt.ylabel('Population') # Population as the dependent variable\n",
    "plt.legend()\n",
    "plt.title('Enhanced Dynamics of Wolbachia Infection in Adult Male Mosquitoes')\n",
    "\n",
    "plt.subplot(1, 3, 2)\n",
    "plt.plot(sol.t, sol.y[4], label='Uninfected') # Plot uninfected individuals\n",
    "plt.plot(sol.t, sol.y[5], label='Infected') # Plot infected individuals\n",
    "plt.xlabel('Time') # Time as the independent variable\n",
    "plt.ylabel('Population') # Population as the dependent variable\n",
    "plt.legend()\n",
    "plt.title('Enhanced Dynamics of Wolbachia Infection in Adult Female Mosquitoes')\n",
    "\n",
    "plt.subplot(1, 3, 3)\n",
    "plt.plot(sol.t, sol.y[0], label='Uninfected') # Plot uninfected individuals\n",
    "plt.plot(sol.t, sol.y[1], label='Infected') # Plot infected individuals\n",
    "plt.xlabel('Time') # Time as the independent variable\n",
    "plt.ylabel('Population') # Population as the dependent variable\n",
    "plt.legend()\n",
    "plt.title('Enhanced Dynamics of Wolbachia Infection in Juvenile Mosquitoes')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
